import Link from "next/link";
import {Arrow,Button,Closing,Eyebrow,FAQ,QuickQuote} from "@/components/site";
export default function Home(){return <>
 <section className="hero"><img className="hero-image" src="/images/hero.webp" alt="Remise des clés d’une voiture devant un bâtiment, à la tombée du jour" fetchPriority="high"/><div className="hero-shade"/><div className="hero-copy"><Eyebrow>Le convoyage automobile, simplement.</Eyebrow><h1>Votre voiture arrive.<br/>Votre journée continue.</h1><p>Un conducteur pour votre voiture.<br/>Du temps retrouvé pour vous.</p></div><div className="hero-bottom"><QuickQuote/><div className="hero-caption"><span>Achat à distance · Déménagement · Livraison</span><span>Votre trajet, étudié sur mesure</span></div></div></section>
 <section className="intro-section section"><div><Eyebrow>01 / L’esprit Relio</Eyebrow><h2>Le soin, à chaque<br/>kilomètre.</h2><p className="large-copy">Votre voiture doit changer d’adresse.<br/>Pas tout votre programme.</p><p className="muted measure">Un billet de train, une journée sur la route, quelqu’un à mobiliser… Récupérer un véhicule peut vite devenir une organisation à part entière. Relio vous aide à préparer son acheminement, du lieu de départ à l’adresse convenue.</p><Link href="/fonctionnement" className="text-link">Découvrir le convoyage <Arrow/></Link></div><figure className="road-figure"><img src="/images/road.webp" alt="Route côtière française au soleil couchant" loading="lazy"/><figcaption>Mêmes routes.<br/>Plus de liberté.</figcaption></figure></section>
 <section className="section needs-section" id="vos-besoins"><div className="section-heading"><div><Eyebrow>02 / À chaque départ, sa raison</Eyebrow><h2>La distance ne devrait<br/>pas compliquer vos projets.</h2></div><p className="muted">Une voiture à récupérer.<br/>Plusieurs bonnes raisons de déléguer.</p></div><div className="needs-list">{[
 ['01','Vous avez trouvé la bonne voiture.','Elle n’est simplement pas à côté. Faites étudier sa récupération chez le vendeur et sa livraison à l’adresse de votre choix.','achat','Achat à distance'],
 ['02','Vous changez de ville.','Pendant que vous préparez votre arrivée, préparez aussi le trajet de votre véhicule. Une logistique de moins dans votre déménagement.','demenagement','Déménagement'],
 ['03','Votre voiture doit rentrer.','Un véhicule resté ailleurs, un emploi du temps chargé ou un trajet que vous ne souhaitez pas conduire : décrivez-nous votre situation.','rapatriement','Rapatriement']
 ].map(([n,t,d,v,l])=><Link key={n} href={`/devis?besoin=${v}`} className="need-row"><span className="row-number">{n}</span><div><span className="small-label">{l}</span><h3>{t}</h3></div><p>{d}</p><Arrow/></Link>)}</div></section>
 <section className="section process-section"><div className="section-heading"><div><Eyebrow>03 / Simple, du début à l’arrivée</Eyebrow><h2>Vous donnez la destination.<br/>On prépare la suite.</h2></div><Link className="text-link" href="/fonctionnement">Toutes les étapes <Arrow/></Link></div><div className="steps">{[['01','Votre trajet','Départ, arrivée, véhicule et date souhaitée. Quelques informations pour comprendre votre besoin.'],['02','Votre proposition','La faisabilité, le prix et les modalités sont précisés avant votre accord.'],['03','La prise en charge','Le rendez-vous et les documents sont préparés avec les personnes concernées.'],['04','La remise des clés','Le véhicule rejoint l’adresse convenue, selon les conditions validées ensemble.']].map(([n,t,d])=><div className="step" key={n}><span>{n}<i/></span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
 <section className="care-section section"><div className="care-visual"><img src="/images/hero.webp" alt="Une remise de véhicule préparée avec soin" loading="lazy"/><div className="image-caption"><span>Le détail compte.</span><span>Au départ comme à l’arrivée.</span></div></div><div className="care-copy"><Eyebrow>04 / Confier ses clés n’est pas anodin</Eyebrow><h2>Moins d’inconnues.<br/>Plus de clarté.</h2><p className="muted">Le prix ne suffit pas à choisir. Vous devez aussi comprendre qui prend en charge votre voiture et dans quelles conditions.</p><div className="proof-line"><span>01</span><div><h3>Un périmètre défini</h3><p>Trajet, rendez-vous, frais et éventuelles contraintes : les modalités sont précisées dans la proposition.</p></div></div><div className="proof-line"><span>02</span><div><h3>Un état des lieux à préparer</h3><p>Photos, kilométrage et réserves : les points à documenter sont expliqués avant la remise du véhicule.</p></div></div><div className="proof-line"><span>03</span><div><h3>Une couverture à vérifier</h3><p>Les garanties applicables à votre mission doivent être confirmées avant votre accord.</p></div></div><Link className="text-link" href="/garanties">Comprendre la prise en charge <Arrow/></Link></div></section>
 <section className="price-section section"><Eyebrow>05 / Un prix qui correspond à votre trajet</Eyebrow><div><h2>Le bon devis commence<br/>par les bonnes informations.</h2><p>Distance, type de véhicule, date et contraintes de remise : votre demande permet de chiffrer une mission réelle. Les frais inclus et les éventuels suppléments sont à préciser avant toute validation.</p></div><div className="price-bottom"><span>Pas de tarif d’appel déconnecté de votre besoin.</span><Button href="/devis">Préparer mon devis</Button></div></section>
 <FAQ/><section className="pro-teaser section"><div><Eyebrow>Vous travaillez dans l’automobile ?</Eyebrow><h2>Vos véhicules bougent.<br/>Votre équipe reste disponible.</h2></div><div><p>Concessions, marchands VO, loueurs et flottes : découvrez le parcours dédié à vos transferts et livraisons.</p><Link href="/professionnels" className="text-link">Découvrir Relio Pro <Arrow/></Link></div></section><Closing/>
 </>}
