"use client";
import Link from "next/link";
import {useRef,useState} from "react";
import {type Quote,validateQuote,todayLocal} from "@/lib/quote";
export default function QuoteForm({initial,enabled}:{initial:Partial<Quote>;enabled:boolean}) {
 const [data,setData]=useState<Quote>({profil:'particulier',depart:'',arrivee:'',date:'',flexible:'oui',besoin:'autre',vehicule:'',energie:'inconnu',roulant:'oui',frequence:'ponctuel',volume:'',entreprise:'',nom:'',email:'',telephone:'',notes:'',website:'',consent:false,...initial});
 const [stage,setStage]=useState(1);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const heading=useRef<HTMLHeadingElement>(null);
 const pro=data.profil==='professionnel';
 function update(key:keyof Quote,value:string|boolean){setData({...data,[key]:value});setError('');}
 function changeStage(n:number){setStage(n);setError('');requestAnimationFrame(()=>heading.current?.focus());}
 function download(){const text=['RELIO — RÉCAPITULATIF DE DEMANDE',enabled?'Récapitulatif — aucun tarif confirmé, aucune réservation.':'Document préparatoire — aucune demande envoyée, aucun tarif confirmé.','',...Object.entries({Profil:data.profil,Départ:data.depart,Arrivée:data.arrivee,Date:data.date||'À convenir',Flexibilité:data.flexible,Besoin:data.besoin,Véhicule:data.vehicule,Énergie:data.energie,'Véhicule roulant':data.roulant,Fréquence:data.frequence,Volume:data.volume,Entreprise:data.entreprise,Nom:data.nom,Email:data.email,Téléphone:data.telephone,Précisions:data.notes}).filter(([,v])=>v).map(([k,v])=>`${k} : ${v}`)].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='relio-ma-demande.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const problem=validateQuote(data,stage);if(problem){setError(problem);return;}if(stage<3){changeStage(stage+1);return;}if(!enabled){download();setDone(true);return;}setBusy(true);setError('');try{const response=await fetch('/api/devis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'L’envoi n’a pas abouti. Veuillez réessayer.');setDone(true);}catch(err){setError(err instanceof Error?err.message:'Impossible d’envoyer votre demande.');}finally{setBusy(false);}}
 if(done)return <div className="quote-form form-success" role="status"><p className="eyebrow">{enabled?'Demande transmise':'Récapitulatif préparé'}</p><h2>{enabled?'Votre trajet est entre nos mains.':'Votre projet est prêt à être partagé.'}</h2><p>{enabled?'Votre demande a été transmise pour étude. Elle ne constitue pas une réservation. La faisabilité et les modalités seront à confirmer.':'Votre récapitulatif a été téléchargé. Aucune demande n’a été envoyée : le service est encore en préparation.'}</p><button className="button button-outline" onClick={download}>Télécharger le récapitulatif <span>↓</span></button><div className="form-actions"><button className="back" onClick={()=>{setDone(false);changeStage(1);}}>← Modifier ma demande</button><Link className="text-link" href="/">Accueil ↗</Link></div></div>;
 return <form className="quote-form" onSubmit={submit}>
  {!enabled&&<div className="demo-note">Version de démonstration : préparez et téléchargez votre demande. Aucun envoi ni réservation à cette étape.</div>}
  <div className="progress" aria-label={`Étape ${stage} sur 3`}><span className={stage>=1?'current':''}>01 / Le trajet</span><span className={stage>=2?'current':''}>02 / Le véhicule</span><span className={stage>=3?'current':''}>03 / Vos coordonnées</span></div>
  <h2 ref={heading} tabIndex={-1}>{stage===1?'Commençons par la route.':stage===2?'Parlons du véhicule.':'À qui s’adresse la proposition ?'}</h2>
  {stage===1&&<><div className="segmented" aria-label="Votre profil"><button type="button" aria-pressed={!pro} className={!pro?'active':''} onClick={()=>update('profil','particulier')}>Particulier</button><button type="button" aria-pressed={pro} className={pro?'active':''} onClick={()=>update('profil','professionnel')}>Professionnel</button></div><div className="form-grid">
   <label>Départ<input autoComplete="off" required maxLength={120} value={data.depart} placeholder="Ville, pays" onChange={e=>update('depart',e.target.value)}/></label><label>Arrivée<input autoComplete="off" required maxLength={120} value={data.arrivee} placeholder="Ville, pays" onChange={e=>update('arrivee',e.target.value)}/></label>
   <label>Date souhaitée<input type="date" min={todayLocal()} value={data.date} required={data.flexible==='non'} onChange={e=>update('date',e.target.value)}/></label><label>Votre date est-elle flexible ?<select value={data.flexible} onChange={e=>update('flexible',e.target.value)}><option value="oui">Oui, à convenir ensemble</option><option value="non">Non, date précise</option></select></label>
   <label className="full-width">Votre besoin<select value={data.besoin} onChange={e=>update('besoin',e.target.value)}><option value="autre">À préciser ensemble</option><option value="achat">Récupération après achat</option><option value="demenagement">Déménagement</option><option value="rapatriement">Rapatriement</option><option value="transfert">Transfert entre sites</option><option value="reprise">Reprise ou restitution</option><option value="livraison">Livraison à un client</option></select></label>
  </div></>}
  {stage===2&&<div className="form-grid">{pro&&<><label className="full-width">Entreprise<input required autoComplete="organization" maxLength={150} value={data.entreprise} onChange={e=>update('entreprise',e.target.value)} placeholder="Nom de votre entreprise"/></label><label>Fréquence<select value={data.frequence} onChange={e=>update('frequence',e.target.value)}><option value="ponctuel">Mission ponctuelle</option><option value="regulier">Besoins réguliers</option></select></label><label>Volume estimatif (facultatif)<input maxLength={100} value={data.volume} onChange={e=>update('volume',e.target.value)} placeholder="Ex. 3 véhicules par mois"/></label></>}
   <label className="full-width">{pro?'Véhicule(s) concerné(s)':'Marque et modèle'}<input required maxLength={150} value={data.vehicule} onChange={e=>update('vehicule',e.target.value)} placeholder={pro?'Ex. berlines, SUV, utilitaires…':'Ex. Peugeot 308'}/></label>
   <label>Énergie<select value={data.energie} onChange={e=>update('energie',e.target.value)}><option value="inconnu">À préciser</option><option value="thermique">Essence / diesel</option><option value="electrique">Électrique</option><option value="hybride">Hybride</option></select></label>
   <label>En état de circuler ?<select value={data.roulant} onChange={e=>update('roulant',e.target.value)}><option value="oui">Oui</option><option value="non">Non</option><option value="inconnu">À vérifier</option></select></label>
   {data.roulant!=='oui'&&<p className="demo-note full-width">Le convoyage par conducteur nécessite un véhicule en état de circuler. Votre besoin devra faire l’objet d’une étude spécifique.</p>}
   <label className="full-width">Précisions utiles (facultatif)<textarea maxLength={2000} value={data.notes} onChange={e=>update('notes',e.target.value)} placeholder="Horaires d’accès, contacts sur place, gabarit, contraintes de livraison…"/></label>
  </div>}
  {stage===3&&<><dl className="summary-list"><div><dt>Trajet</dt><dd>{data.depart} → {data.arrivee}</dd></div><div><dt>Date</dt><dd>{data.date||'À convenir'}{data.flexible==='oui'?' · flexible':''}</dd></div><div><dt>Véhicule</dt><dd>{data.vehicule}</dd></div>{pro&&<div><dt>Entreprise</dt><dd>{data.entreprise}</dd></div>}</dl><div className="form-grid" style={{marginTop:25}}><label className="full-width">Nom complet<input autoComplete="name" required maxLength={150} value={data.nom} onChange={e=>update('nom',e.target.value)}/></label><label className="full-width">Email<input autoComplete="email" type="email" required maxLength={200} value={data.email} onChange={e=>update('email',e.target.value)}/></label><label className="full-width">Téléphone (facultatif)<input autoComplete="tel" type="tel" maxLength={30} value={data.telephone} onChange={e=>update('telephone',e.target.value)}/></label></div><label className="consent"><input type="checkbox" required checked={data.consent} onChange={e=>update('consent',e.target.checked)}/><span>J’ai lu les <Link href="/confidentialite" target="_blank">informations de confidentialité</Link>. {enabled?'Mes coordonnées seront utilisées pour étudier cette demande.':'En démonstration, les informations ne sont pas envoyées.'}</span></label></>}
  <label className="hidden-trap" aria-hidden="true">Votre site web<input tabIndex={-1} autoComplete="off" value={data.website} onChange={e=>update('website',e.target.value)}/></label>
  {error&&<p className="form-error" role="alert">{error}</p>}
  <div className="form-actions">{stage>1?<button type="button" className="back" onClick={()=>changeStage(stage-1)}>← Retour</button>:<span/>}<button className="button" type="submit" disabled={busy}>{busy?'Envoi en cours…':stage<3?'Continuer':enabled?'Envoyer ma demande':'Télécharger ma demande'}<span aria-hidden="true">{stage<3?'→':enabled?'↗':'↓'}</span></button></div><p className="form-help">{stage<3?'Vous pourrez vérifier et modifier les informations avant de terminer.':'Une demande ne vaut pas réservation. Aucun paiement à cette étape.'}</p>
 </form>;
}
