import Link from "next/link";
export const Arrow=()=> <span aria-hidden="true">↗</span>;
export function Button({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}) {return <Link className={`button ${light?'button-light':''}`} href={href}>{children}<Arrow/></Link>}
export function Eyebrow({children}:{children:React.ReactNode}) {return <p className="eyebrow">{children}</p>}
export function QuickQuote({pro=false}:{pro?:boolean}) {return <form action="/devis" method="get" className="quick-quote">
 <input type="hidden" name="profil" value={pro?'professionnel':'particulier'}/>
 <label>Départ<input name="depart" placeholder="Ville de départ" aria-label="Ville de départ" required maxLength={120}/></label>
 <label>Arrivée<input name="arrivee" placeholder="Ville d’arrivée" aria-label="Ville d’arrivée" required maxLength={120}/></label>
 <label>Date souhaitée<input name="date" type="date" aria-label="Date souhaitée"/></label>
 <button type="submit" className="button">Préparer mon trajet <span aria-hidden="true">→</span></button>
 </form>}
export function FAQ({pro=false}:{pro?:boolean}) {const items=pro?[
 ['Nous avons déjà un prestataire. Peut-on vous solliciter ponctuellement ?','Oui. Votre demande peut concerner une seule mission, un renfort ou un trajet spécifique. La faisabilité et la disponibilité sont étudiées avant toute confirmation.'],
 ['Pouvez-vous livrer directement notre client ?','La livraison à un particulier ou à une entreprise peut faire partie de la demande. Précisez le contact, le créneau souhaité et les documents à remettre. Le contenu de la prestation est convenu avant le départ.'],
 ['Comment sont chiffrés les besoins réguliers ?','Indiquez vos axes, les types de véhicules et une fréquence, même estimative. Chaque proposition tient compte des contraintes réelles : accès aux sites, délais, volume et organisation des trajets.'],
 ['Qui conduit les véhicules ?','Les missions peuvent être réalisées par le fondateur de Relio ou par un convoyeur partenaire. L’organisation retenue et les modalités de prise en charge sont précisées avant la mission.'],
 ['Les utilitaires et les trajets internationaux sont-ils possibles ?','Précisez le gabarit, le poids du véhicule et les pays concernés. L’acceptation dépend du véhicule, des documents nécessaires, du trajet et de la couverture applicable.']
 ]:[
 ['Qu’est-ce que le convoyage automobile ?','Un conducteur prend en charge votre véhicule et le conduit jusqu’à l’adresse convenue. Le véhicule roule donc par ses propres moyens : il doit être en état de circuler et le trajet ajoute des kilomètres au compteur.'],
 ['Puis-je faire récupérer une voiture que je viens d’acheter ?','Oui, vous pouvez préparer une demande de récupération auprès d’un vendeur professionnel ou particulier. La vente, les documents et l’autorisation de remise doivent être finalisés. Le convoyage ne remplace pas une expertise mécanique avant achat.'],
 ['Combien coûte un convoyage ?','Le tarif dépend du trajet, du véhicule, des dates et des contraintes de prise en charge. Le devis doit préciser les frais inclus, notamment carburant et péages, ainsi que les éventuels suppléments. Aucun paiement n’est demandé pour préparer votre demande.'],
 ['Mon véhicule est-il couvert pendant le trajet ?','Les conditions de couverture applicables à votre véhicule et à votre trajet doivent être confirmées avant la mission : garanties, exclusions et franchise éventuelle. Vous pouvez demander les justificatifs avant d’accepter la proposition.'],
 ['Et si mon véhicule ne roule pas ?','Le convoyage par conducteur concerne les véhicules en état de circuler. Signalez toute panne ou restriction dans votre demande : une solution de transport différente devra être étudiée.'],
 ['Peut-on organiser un trajet à l’étranger ?','Les demandes internationales sont étudiées selon les pays, les documents disponibles et les conditions de la mission. Indiquez les deux pays dès votre demande ; aucune destination n’est confirmée automatiquement.']
 ]; return <section className="section faq-section" id="questions"><div><Eyebrow>Vos questions, nos réponses</Eyebrow><h2>Tout commence<br/>par la confiance.</h2><p className="muted">Un point à éclaircir avant de nous confier les clés ?</p><Link className="text-link" href="/contact">Parlons de votre trajet <Arrow/></Link></div><div className="faq-list">{items.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>}
export function Closing({pro=false}:{pro?:boolean}) {return <section className="closing"><Eyebrow>Le prochain trajet commence ici</Eyebrow><div><h2>{pro?<>Un véhicule à déplacer.<br/>Une solution à organiser.</>:<>Votre voiture a de la route.<br/>Vous avez mieux à faire.</>}</h2><Button href={pro?'/devis?profil=professionnel':'/devis'} light>Préparer ma demande</Button></div><p>Trajet, véhicule, date. Nous commençons par l’essentiel.</p></section>}
export function Footer(){return <footer className="site-footer"><div className="footer-top"><div><Link href="/" className="logo">relio<span>.</span></Link><p>Le convoyage automobile,<br/>simplement.</p></div><div><p className="footer-label">Votre trajet</p><Link href="/">Particuliers</Link><Link href="/professionnels">Professionnels</Link><Link href="/devis">Demander un devis</Link></div><div><p className="footer-label">Relio</p><Link href="/fonctionnement">Comment ça marche</Link><Link href="/garanties">Prise en charge & garanties</Link><Link href="/contact">Nous contacter</Link></div><div className="footer-note"><p className="footer-label">D’un point A à votre prochain chapitre.</p><p>France & international<br/>Trajets étudiés sur demande.</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Relio</span><span><Link href="/mentions-legales">Mentions légales</Link><Link href="/confidentialite">Confidentialité</Link></span><span>Le soin, à chaque kilomètre.</span></div></footer>}
export function PageIntro({label,title,text}:{label:string;title:React.ReactNode;text:string}) {return <section className="page-intro section"><Eyebrow>{label}</Eyebrow><h1>{title}</h1><p>{text}</p></section>}
