import type { Metadata } from "next";
import Link from "next/link";
import {Arrow,Button,Closing,Eyebrow,FAQ,QuickQuote} from "@/components/site";
export const metadata:Metadata={title:"Convoyage pour concessions, loueurs et flottes",description:"Transferts entre sites, récupérations et livraisons à vos clients. Préparez vos missions ponctuelles ou vos besoins réguliers avec Relio."};
export default function Pro(){return <>
 <section className="hero pro-hero"><img className="hero-image" src="/images/hero.webp" alt="Remise d’un véhicule par un conducteur à un client" fetchPriority="high"/><div className="hero-shade"/><div className="hero-copy"><Eyebrow>Relio / Pour les professionnels</Eyebrow><h1>Vos véhicules avancent.<br/>Vos équipes restent<br/>disponibles.</h1><p>Transferts, récupérations et livraisons clients.<br/>Le convoyage au service de votre activité.</p></div><div className="hero-bottom"><QuickQuote pro/><div className="hero-caption"><span>Concessions · Marchands VO · Loueurs · Flottes</span><Link href="/devis?profil=professionnel&frequence=regulier">Des besoins réguliers ? Parlons-en ↗</Link></div></div></section>
 <section className="section pro-intro"><Eyebrow>01 / Le véhicule n’est qu’une partie du trajet</Eyebrow><div className="split-heading"><h2>Derrière chaque livraison,<br/>votre organisation.</h2><div><p className="large-copy">Un commercial sur la route.<br/>Une agence qui attend un véhicule.<br/>Un client qui attend ses clés.</p><p className="muted">Relio vous propose de déléguer le déplacement. Vous gardez la main sur les contraintes et les modalités de la mission.</p></div></div><div className="sector-tags"><span>Concessions automobiles</span><span>Marchands de véhicules d’occasion</span><span>Loueurs</span><span>Gestionnaires de flotte</span></div></section>
 <section className="section needs-section"><div className="section-heading"><div><Eyebrow>02 / Vos besoins, concrètement</Eyebrow><h2>Le bon véhicule.<br/>Au bon endroit.</h2></div><p className="muted">Une demande précise.<br/>Une organisation adaptée.</p></div><div className="needs-list">{[['01','Transférer entre vos sites','Déplacer un véhicule entre concessions, agences ou établissements, selon les disponibilités et les horaires de réception.','transfert'],['02','Récupérer un véhicule','Préparer une récupération après achat, une reprise ou une restitution avec les interlocuteurs concernés.','reprise'],['03','Livrer votre client','Organiser la remise du véhicule à l’adresse convenue. Les consignes et documents à transmettre sont définis avec vous.','livraison']].map(([n,t,d,v])=><Link className="need-row" href={`/devis?profil=professionnel&besoin=${v}`} key={n}><span className="row-number">{n}</span><h3>{t}</h3><p>{d}</p><Arrow/></Link>)}</div></section>
 <section className="section editorial-split"><div><Eyebrow>03 / Votre dernière impression compte</Eyebrow><h2>La vente est conclue.<br/>L’expérience continue.</h2><p className="large-copy">La remise des clés fait encore partie de votre relation client.</p><p className="muted">Contact du destinataire, rendez-vous, état du véhicule, documents à remettre : préparez les détails avec Relio pour que la livraison s’inscrive dans la continuité de votre service.</p><Button href="/devis?profil=professionnel&besoin=livraison">Préparer une livraison</Button></div><div className="editorial-image"><img src="/images/hero.webp" alt="Remise des clés à un destinataire" loading="lazy"/></div></section>
 <section className="section reinforcement"><Eyebrow>04 / Vous avez déjà votre organisation</Eyebrow><h2>Gardez vos habitudes.<br/>Ajoutez une possibilité.</h2><div className="reinforcement-bottom"><p>Une mission que votre prestataire habituel ne peut pas prendre ? Une équipe déjà occupée ? Commencez par un besoin ponctuel. Chaque demande est étudiée selon le trajet et les disponibilités.</p><Link className="text-link" href="/devis?profil=professionnel">Proposer une première mission <Arrow/></Link></div></section>
 <section className="section process-section"><div className="section-heading"><div><Eyebrow>05 / Une mission préparée ensemble</Eyebrow><h2>Les détails réglés<br/>avant les kilomètres.</h2></div></div><div className="steps">{[['01','Votre besoin','Trajet, véhicule, contacts, échéance et particularités des sites.'],['02','Notre proposition','Faisabilité, disponibilités, prix et modalités à valider.'],['03','La coordination','Les instructions de départ et de remise sont partagées.'],['04','La clôture','La remise et les éventuelles réserves sont documentées selon les modalités convenues.']].map(([n,t,d])=><div className="step" key={n}><span>{n}<i/></span><h3>{t}</h3><p>{d}</p></div>)}</div><Link className="text-link" href="/garanties">Prise en charge et garanties <Arrow/></Link></section>
 <section className="section recurring"><div><Eyebrow>06 / Vos besoins réguliers</Eyebrow><h2>Parlons de vos flux.<br/>Pas seulement d’un trajet.</h2></div><div><p>Des axes récurrents, plusieurs véhicules ou un besoin de renfort ? Indiquez votre fréquence, même estimative. Nous pourrons étudier une organisation cohérente avec votre activité.</p><Button href="/devis?profil=professionnel&frequence=regulier">Présenter mes besoins</Button></div></section><FAQ pro/><Closing pro/>
 </>}
